name: automatic-workflow-dev
on:
  pull_request:
    types: [opened, closed]
    branches:
    - develop
  # push:
  #   branches:
  #   - feature/*
jobs:
  Checkout-Repo:
    runs-on: ubuntu-latest
    steps:
    - name: checkout from git
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
