name: automatic-workflow-dev
on:
  pull_request:
    types: [opened, closed]
    branches:
    - develop
  push:
    branches:
    - feature/*
jobs:
  Checkout-Repo:
    runs-on: ubuntu-latest
    steps:
    - name: checkout from git
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
  Sonar-Scan:
    runs-on: ubuntu-latest
    needs: Checkout-Repo
    steps:
    - name: checkout from git
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

  Backend-CI:
    if: github.event_name == 'pull_request'
    needs: Sonar-Scan
    runs-on: ubuntu-latest
    steps:
    - name: checkout from git
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

  Backend-BlackDuck:
    runs-on: ubuntu-latest
    needs: Backend-CI
    steps:
    - name: checkout from git
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

  Backend-CD:
    if: ${{ github.event.pull_request.merged }}
    needs: Backend-BlackDuck
    runs-on: ubuntu-latest
    steps:
    - name: checkout from git
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
